Ivan
AndreyeuIvan/game_nerd pull request #7
Opened 2022-02-17 20:15 UTC by AndreyeuIvan

game-model-n-celery
Created nerdy-command.
Logic is following:
1. Creates request to igb.
2. In a cycle takes the name of a game.
3. Put it into api request of twitter.
4. Saves obj of twitter into DB.
5. in a cycle attributes of the game from igb saved into .json file.
6. Creates fixture.

2022-02-18 08:52 UTC, Satevg requested changes

2022-02-18 08:52 UTC, Satevg commented on games/service_igdb.py
> +print(token_twitch)
remove print please

2022-02-18 08:52 UTC, Satevg commented on games/views.py
> +        context = {"game": Game.objects.get(pk=id)}
again, better to remove except and use `get_object_or_404`

2022-02-18 08:52 UTC, Satevg commented on games/management/commands/nerdy.py
> +            my_format += [
probably more pythonic it'll be like

my_format = [{"model": "games.game", "pk": game.get("id"), "fields": {and so on}} for game in igb_json]

---------------------------------

Optional: enable style-checks/fixes with `black` package.

2022-02-21 08:35 UTC, Satevg approved these changes

2022-02-21 11:08 UTC, merged

2022-02-21 11:09 UTC, AndreyeuIvan commented
Task to create command-django - done